In [62]:
import pandas as pd 

df = pd.read_csv("short_messy_ecommerce_50_rows.csv")
df

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
1,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
2,3,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
3,4,Neha,Delhi,Mouse,NaN,Cash,08-01-2025,3.0
4,5,Rohan,Mumbai,Monitor,15000.0,Debit Card,08-01-2025,4.0
5,6,Sneha,NaN,Tablet,22000.0,UPI,10-01-2025,5.0
6,7,Karan,jaipur,Keyboard,1800.0,Wallet,11-01-2025,3.0
7,8,Isha,Lucknow,NaN,6000.0,UPI,12-01-2025,4.0
8,9,Arjun,Agra,Camera,42000.0,Credit Card,13-01-2025,5.0
9,10,Pooja,Gwalior,Printer,12000.0,Cash,14-01-2025,2.0
10,11,Aarav,Bhopal,NaN,5500.0,UPI,15-01-2025,4.0
11,12,Riya,NaN,Router,2800.0,Debit Card,16-01-2025,3.0
12,13,Simran,Delhi,Webcam,3000.0,UPI,17-01-2025,5.0
13,14,Vivek,Mumbai,Laptop,62000.0,Credit Card,18-01-2025,4.0
14,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
15,16,Mohit,Jaipur,Mouse,850.0,Cash,20-01-2025,3.0
16,17,Kavya,Lucknow,Tablet,21000.0,Wallet,21-01-2025,4.0
17,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
18,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
19,20,Meera,Bhopal,Keyboard,2000.0,UPI,24-01-2025,4.0
20,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
21,22,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
22,23,Rohit,Delhi,Phone,29000.0,upi,26-01-2025,4.0
23,24,Priya,Bhopal,Tablet,22000.0,Credit Card,NaN,5.0
24,25,Neha,Delhi,Mouse,900.0,NaN,28-01-2025,NaN
25,26,Karan,Jaipur,Laptop,58000.0,UPI,29-01-2025,4.0
26,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
27,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
28,29,Pooja,Gwalior,Printer,12000.0,Cash,31-01-2025,NaN
29,30,Aarav,NaN,SSD,5500.0,UPI,01-02-2025,6.0
30,31,Riya,Indore,Router,2800.0,Debit Card,02-02-2025,4.0
31,32,Simran,Delhi,Webcam,3000.0,upi,03-02-2025,5.0
32,33,Vivek,Mumbai,Laptop,999999.0,Credit Card,NaN,4.0
33,34,Ananya,Pune,Phone,31000.0,UPI,05-02-2025,5.0
34,35,Mohit,Jaipur,Mouse,850.0,cash,06-02-2025,3.0
35,36,Kavya,Lucknow,NaN,21000.0,Wallet,07-02-2025,4.0
36,37,Nisha,Agra,Headphones,4000.0,UPI,08-02-2025,5.0
37,38,Dev,Gwalior,Monitor,14000.0,Debit Card,09-02-2025,3.0
38,39,Meera,Bhopal,Keyboard,2000.0,UPI,10-02-2025,4.0
39,40,Amit,NaN,Laptop,55000.0,UPI,11-02-2025,5.0
40,41,NaN,Indore,Phone,28000.0,Credit Card,12-02-2025,4.0
41,42,Rohan,Mumbai,Monitor,NaN,Debit Card,13-02-2025,4.0
42,43,Sneha,Pune,Tablet,22000.0,NaN,NaN,5.0
43,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
44,45,Isha,Lucknow,Smartwatch,6000.0,UPI,15-02-2025,4.0
45,46,Arjun,Agra,Camera,42000.0,Credit Card,16-02-2025,5.0
46,47,Pooja,NaN,Printer,12000.0,Cash,17-02-2025,NaN
47,48,Aarav,Bhopal,SSD,5500.0,UPI,18-02-2025,4.0
48,49,Riya,Indore,Router,2800.0,Debit Card,19-02-2025,3.0
49,50,Simran,Delhi,Webcam,3000.0,UPI,20-02-2025,5.0

In [63]:
# Handling Missing Values

In [64]:
# Check for missing values
df.isnull()

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,True,False,False,False,False
11,False,False,True,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,True,False
24,False,False,False,False,False,True,False,True
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,True
29,False,False,True,False,False,False,False,False
30,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,True,False
33,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False
35,False,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False
39,False,False,True,False,False,False,False,False
40,False,True,False,False,False,False,False,False
41,False,False,False,False,True,False,False,False
42,False,False,False,False,False,True,True,False
43,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False
46,False,False,True,False,False,False,False,True
47,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False

In [65]:
df.isnull().sum()

order_id          0
customer_name     1
city              5
product           3
amount            2
payment_method    2
order_date        3
rating            3
dtype: int64

In [66]:
# Drop Missing Data
df.dropna()

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
1,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
2,3,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
4,5,Rohan,Mumbai,Monitor,15000.0,Debit Card,08-01-2025,4.0
6,7,Karan,jaipur,Keyboard,1800.0,Wallet,11-01-2025,3.0
8,9,Arjun,Agra,Camera,42000.0,Credit Card,13-01-2025,5.0
9,10,Pooja,Gwalior,Printer,12000.0,Cash,14-01-2025,2.0
12,13,Simran,Delhi,Webcam,3000.0,UPI,17-01-2025,5.0
13,14,Vivek,Mumbai,Laptop,62000.0,Credit Card,18-01-2025,4.0
14,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
15,16,Mohit,Jaipur,Mouse,850.0,Cash,20-01-2025,3.0
16,17,Kavya,Lucknow,Tablet,21000.0,Wallet,21-01-2025,4.0
17,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
18,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
19,20,Meera,Bhopal,Keyboard,2000.0,UPI,24-01-2025,4.0
20,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
21,22,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
22,23,Rohit,Delhi,Phone,29000.0,upi,26-01-2025,4.0
25,26,Karan,Jaipur,Laptop,58000.0,UPI,29-01-2025,4.0
26,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
27,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
30,31,Riya,Indore,Router,2800.0,Debit Card,02-02-2025,4.0
31,32,Simran,Delhi,Webcam,3000.0,upi,03-02-2025,5.0
33,34,Ananya,Pune,Phone,31000.0,UPI,05-02-2025,5.0
34,35,Mohit,Jaipur,Mouse,850.0,cash,06-02-2025,3.0
36,37,Nisha,Agra,Headphones,4000.0,UPI,08-02-2025,5.0
37,38,Dev,Gwalior,Monitor,14000.0,Debit Card,09-02-2025,3.0
38,39,Meera,Bhopal,Keyboard,2000.0,UPI,10-02-2025,4.0
43,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
44,45,Isha,Lucknow,Smartwatch,6000.0,UPI,15-02-2025,4.0
45,46,Arjun,Agra,Camera,42000.0,Credit Card,16-02-2025,5.0
47,48,Aarav,Bhopal,SSD,5500.0,UPI,18-02-2025,4.0
48,49,Riya,Indore,Router,2800.0,Debit Card,19-02-2025,3.0
49,50,Simran,Delhi,Webcam,3000.0,UPI,20-02-2025,5.0

In [67]:
df.dropna(axis=1)

    order_id
0          1
1          1
2          3
3          4
4          5
5          6
6          7
7          8
8          9
9         10
10        11
11        12
12        13
13        14
14        15
15        16
16        17
17        18
18        19
19        20
20        15
21        22
22        23
23        24
24        25
25        26
26        18
27        19
28        29
29        30
30        31
31        32
32        33
33        34
34        35
35        36
36        37
37        38
38        39
39        40
40        41
41        42
42        43
43        15
44        45
45        46
46        47
47        48
48        49
49        50

In [68]:
# Fill Missing Data
df.fillna(0)

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
1,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
2,3,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
3,4,Neha,Delhi,Mouse,0.0,Cash,08-01-2025,3.0
4,5,Rohan,Mumbai,Monitor,15000.0,Debit Card,08-01-2025,4.0
5,6,Sneha,0,Tablet,22000.0,UPI,10-01-2025,5.0
6,7,Karan,jaipur,Keyboard,1800.0,Wallet,11-01-2025,3.0
7,8,Isha,Lucknow,0,6000.0,UPI,12-01-2025,4.0
8,9,Arjun,Agra,Camera,42000.0,Credit Card,13-01-2025,5.0
9,10,Pooja,Gwalior,Printer,12000.0,Cash,14-01-2025,2.0
10,11,Aarav,Bhopal,0,5500.0,UPI,15-01-2025,4.0
11,12,Riya,0,Router,2800.0,Debit Card,16-01-2025,3.0
12,13,Simran,Delhi,Webcam,3000.0,UPI,17-01-2025,5.0
13,14,Vivek,Mumbai,Laptop,62000.0,Credit Card,18-01-2025,4.0
14,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
15,16,Mohit,Jaipur,Mouse,850.0,Cash,20-01-2025,3.0
16,17,Kavya,Lucknow,Tablet,21000.0,Wallet,21-01-2025,4.0
17,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
18,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
19,20,Meera,Bhopal,Keyboard,2000.0,UPI,24-01-2025,4.0
20,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
21,22,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
22,23,Rohit,Delhi,Phone,29000.0,upi,26-01-2025,4.0
23,24,Priya,Bhopal,Tablet,22000.0,Credit Card,0,5.0
24,25,Neha,Delhi,Mouse,900.0,0,28-01-2025,0.0
25,26,Karan,Jaipur,Laptop,58000.0,UPI,29-01-2025,4.0
26,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
27,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
28,29,Pooja,Gwalior,Printer,12000.0,Cash,31-01-2025,0.0
29,30,Aarav,0,SSD,5500.0,UPI,01-02-2025,6.0
30,31,Riya,Indore,Router,2800.0,Debit Card,02-02-2025,4.0
31,32,Simran,Delhi,Webcam,3000.0,upi,03-02-2025,5.0
32,33,Vivek,Mumbai,Laptop,999999.0,Credit Card,0,4.0
33,34,Ananya,Pune,Phone,31000.0,UPI,05-02-2025,5.0
34,35,Mohit,Jaipur,Mouse,850.0,cash,06-02-2025,3.0
35,36,Kavya,Lucknow,0,21000.0,Wallet,07-02-2025,4.0
36,37,Nisha,Agra,Headphones,4000.0,UPI,08-02-2025,5.0
37,38,Dev,Gwalior,Monitor,14000.0,Debit Card,09-02-2025,3.0
38,39,Meera,Bhopal,Keyboard,2000.0,UPI,10-02-2025,4.0
39,40,Amit,0,Laptop,55000.0,UPI,11-02-2025,5.0
40,41,0,Indore,Phone,28000.0,Credit Card,12-02-2025,4.0
41,42,Rohan,Mumbai,Monitor,0.0,Debit Card,13-02-2025,4.0
42,43,Sneha,Pune,Tablet,22000.0,0,0,5.0
43,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
44,45,Isha,Lucknow,Smartwatch,6000.0,UPI,15-02-2025,4.0
45,46,Arjun,Agra,Camera,42000.0,Credit Card,16-02-2025,5.0
46,47,Pooja,0,Printer,12000.0,Cash,17-02-2025,0.0
47,48,Aarav,Bhopal,SSD,5500.0,UPI,18-02-2025,4.0
48,49,Riya,Indore,Router,2800.0,Debit Card,19-02-2025,3.0
49,50,Simran,Delhi,Webcam,3000.0,UPI,20-02-2025,5.0

In [69]:
df["amount"].fillna(df["amount"].mean())

0      55000.000000
1      55000.000000
2       3500.000000
3      38006.229167
4      15000.000000
5      22000.000000
6       1800.000000
7       6000.000000
8      42000.000000
9      12000.000000
10      5500.000000
11      2800.000000
12      3000.000000
13     62000.000000
14     31000.000000
15       850.000000
16     21000.000000
17      4000.000000
18     14000.000000
19      2000.000000
20     31000.000000
21      3500.000000
22     29000.000000
23     22000.000000
24       900.000000
25     58000.000000
26      4000.000000
27     14000.000000
28     12000.000000
29      5500.000000
30      2800.000000
31      3000.000000
32    999999.000000
33     31000.000000
34       850.000000
35     21000.000000
36      4000.000000
37     14000.000000
38      2000.000000
39     55000.000000
40     28000.000000
41     38006.229167
42     22000.000000
43     31000.000000
44      6000.000000
45     42000.000000
46     12000.000000
47      5500.000000
48      2800.000000
49      3000.000000
Name: amount, dtype: float64

In [70]:
df.ffill()

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
1,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
2,3,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
3,4,Neha,Delhi,Mouse,3500.0,Cash,08-01-2025,3.0
4,5,Rohan,Mumbai,Monitor,15000.0,Debit Card,08-01-2025,4.0
5,6,Sneha,Mumbai,Tablet,22000.0,UPI,10-01-2025,5.0
6,7,Karan,jaipur,Keyboard,1800.0,Wallet,11-01-2025,3.0
7,8,Isha,Lucknow,Keyboard,6000.0,UPI,12-01-2025,4.0
8,9,Arjun,Agra,Camera,42000.0,Credit Card,13-01-2025,5.0
9,10,Pooja,Gwalior,Printer,12000.0,Cash,14-01-2025,2.0
10,11,Aarav,Bhopal,Printer,5500.0,UPI,15-01-2025,4.0
11,12,Riya,Bhopal,Router,2800.0,Debit Card,16-01-2025,3.0
12,13,Simran,Delhi,Webcam,3000.0,UPI,17-01-2025,5.0
13,14,Vivek,Mumbai,Laptop,62000.0,Credit Card,18-01-2025,4.0
14,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
15,16,Mohit,Jaipur,Mouse,850.0,Cash,20-01-2025,3.0
16,17,Kavya,Lucknow,Tablet,21000.0,Wallet,21-01-2025,4.0
17,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
18,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
19,20,Meera,Bhopal,Keyboard,2000.0,UPI,24-01-2025,4.0
20,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
21,22,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
22,23,Rohit,Delhi,Phone,29000.0,upi,26-01-2025,4.0
23,24,Priya,Bhopal,Tablet,22000.0,Credit Card,26-01-2025,5.0
24,25,Neha,Delhi,Mouse,900.0,Credit Card,28-01-2025,5.0
25,26,Karan,Jaipur,Laptop,58000.0,UPI,29-01-2025,4.0
26,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
27,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
28,29,Pooja,Gwalior,Printer,12000.0,Cash,31-01-2025,3.0
29,30,Aarav,Gwalior,SSD,5500.0,UPI,01-02-2025,6.0
30,31,Riya,Indore,Router,2800.0,Debit Card,02-02-2025,4.0
31,32,Simran,Delhi,Webcam,3000.0,upi,03-02-2025,5.0
32,33,Vivek,Mumbai,Laptop,999999.0,Credit Card,03-02-2025,4.0
33,34,Ananya,Pune,Phone,31000.0,UPI,05-02-2025,5.0
34,35,Mohit,Jaipur,Mouse,850.0,cash,06-02-2025,3.0
35,36,Kavya,Lucknow,Mouse,21000.0,Wallet,07-02-2025,4.0
36,37,Nisha,Agra,Headphones,4000.0,UPI,08-02-2025,5.0
37,38,Dev,Gwalior,Monitor,14000.0,Debit Card,09-02-2025,3.0
38,39,Meera,Bhopal,Keyboard,2000.0,UPI,10-02-2025,4.0
39,40,Amit,Bhopal,Laptop,55000.0,UPI,11-02-2025,5.0
40,41,Amit,Indore,Phone,28000.0,Credit Card,12-02-2025,4.0
41,42,Rohan,Mumbai,Monitor,28000.0,Debit Card,13-02-2025,4.0
42,43,Sneha,Pune,Tablet,22000.0,Debit Card,13-02-2025,5.0
43,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
44,45,Isha,Lucknow,Smartwatch,6000.0,UPI,15-02-2025,4.0
45,46,Arjun,Agra,Camera,42000.0,Credit Card,16-02-2025,5.0
46,47,Pooja,Agra,Printer,12000.0,Cash,17-02-2025,5.0
47,48,Aarav,Bhopal,SSD,5500.0,UPI,18-02-2025,4.0
48,49,Riya,Indore,Router,2800.0,Debit Card,19-02-2025,3.0
49,50,Simran,Delhi,Webcam,3000.0,UPI,20-02-2025,5.0

In [71]:
df.bfill()

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
1,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
2,3,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
3,4,Neha,Delhi,Mouse,15000.0,Cash,08-01-2025,3.0
4,5,Rohan,Mumbai,Monitor,15000.0,Debit Card,08-01-2025,4.0
5,6,Sneha,jaipur,Tablet,22000.0,UPI,10-01-2025,5.0
6,7,Karan,jaipur,Keyboard,1800.0,Wallet,11-01-2025,3.0
7,8,Isha,Lucknow,Camera,6000.0,UPI,12-01-2025,4.0
8,9,Arjun,Agra,Camera,42000.0,Credit Card,13-01-2025,5.0
9,10,Pooja,Gwalior,Printer,12000.0,Cash,14-01-2025,2.0
10,11,Aarav,Bhopal,Router,5500.0,UPI,15-01-2025,4.0
11,12,Riya,Delhi,Router,2800.0,Debit Card,16-01-2025,3.0
12,13,Simran,Delhi,Webcam,3000.0,UPI,17-01-2025,5.0
13,14,Vivek,Mumbai,Laptop,62000.0,Credit Card,18-01-2025,4.0
14,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
15,16,Mohit,Jaipur,Mouse,850.0,Cash,20-01-2025,3.0
16,17,Kavya,Lucknow,Tablet,21000.0,Wallet,21-01-2025,4.0
17,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
18,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
19,20,Meera,Bhopal,Keyboard,2000.0,UPI,24-01-2025,4.0
20,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
21,22,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
22,23,Rohit,Delhi,Phone,29000.0,upi,26-01-2025,4.0
23,24,Priya,Bhopal,Tablet,22000.0,Credit Card,28-01-2025,5.0
24,25,Neha,Delhi,Mouse,900.0,UPI,28-01-2025,4.0
25,26,Karan,Jaipur,Laptop,58000.0,UPI,29-01-2025,4.0
26,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
27,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
28,29,Pooja,Gwalior,Printer,12000.0,Cash,31-01-2025,6.0
29,30,Aarav,Indore,SSD,5500.0,UPI,01-02-2025,6.0
30,31,Riya,Indore,Router,2800.0,Debit Card,02-02-2025,4.0
31,32,Simran,Delhi,Webcam,3000.0,upi,03-02-2025,5.0
32,33,Vivek,Mumbai,Laptop,999999.0,Credit Card,05-02-2025,4.0
33,34,Ananya,Pune,Phone,31000.0,UPI,05-02-2025,5.0
34,35,Mohit,Jaipur,Mouse,850.0,cash,06-02-2025,3.0
35,36,Kavya,Lucknow,Headphones,21000.0,Wallet,07-02-2025,4.0
36,37,Nisha,Agra,Headphones,4000.0,UPI,08-02-2025,5.0
37,38,Dev,Gwalior,Monitor,14000.0,Debit Card,09-02-2025,3.0
38,39,Meera,Bhopal,Keyboard,2000.0,UPI,10-02-2025,4.0
39,40,Amit,Indore,Laptop,55000.0,UPI,11-02-2025,5.0
40,41,Rohan,Indore,Phone,28000.0,Credit Card,12-02-2025,4.0
41,42,Rohan,Mumbai,Monitor,22000.0,Debit Card,13-02-2025,4.0
42,43,Sneha,Pune,Tablet,22000.0,UPI,19-01-2025,5.0
43,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
44,45,Isha,Lucknow,Smartwatch,6000.0,UPI,15-02-2025,4.0
45,46,Arjun,Agra,Camera,42000.0,Credit Card,16-02-2025,5.0
46,47,Pooja,Bhopal,Printer,12000.0,Cash,17-02-2025,4.0
47,48,Aarav,Bhopal,SSD,5500.0,UPI,18-02-2025,4.0
48,49,Riya,Indore,Router,2800.0,Debit Card,19-02-2025,3.0
49,50,Simran,Delhi,Webcam,3000.0,UPI,20-02-2025,5.0

In [72]:
# Detecting and Removing Duplicates
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22    False
23    False
24    False
25    False
26     True
27     True
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [73]:
df.drop_duplicates()

,order_id,customer_name,city,product,amount,payment_method,order_date,rating
0,1,Amit,Gwalior,Laptop,55000.0,UPI,05-01-2025,5.0
2,3,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
3,4,Neha,Delhi,Mouse,NaN,Cash,08-01-2025,3.0
4,5,Rohan,Mumbai,Monitor,15000.0,Debit Card,08-01-2025,4.0
5,6,Sneha,NaN,Tablet,22000.0,UPI,10-01-2025,5.0
6,7,Karan,jaipur,Keyboard,1800.0,Wallet,11-01-2025,3.0
7,8,Isha,Lucknow,NaN,6000.0,UPI,12-01-2025,4.0
8,9,Arjun,Agra,Camera,42000.0,Credit Card,13-01-2025,5.0
9,10,Pooja,Gwalior,Printer,12000.0,Cash,14-01-2025,2.0
10,11,Aarav,Bhopal,NaN,5500.0,UPI,15-01-2025,4.0
11,12,Riya,NaN,Router,2800.0,Debit Card,16-01-2025,3.0
12,13,Simran,Delhi,Webcam,3000.0,UPI,17-01-2025,5.0
13,14,Vivek,Mumbai,Laptop,62000.0,Credit Card,18-01-2025,4.0
14,15,Ananya,Pune,Phone,31000.0,UPI,19-01-2025,5.0
15,16,Mohit,Jaipur,Mouse,850.0,Cash,20-01-2025,3.0
16,17,Kavya,Lucknow,Tablet,21000.0,Wallet,21-01-2025,4.0
17,18,Nisha,Agra,Headphones,4000.0,UPI,22-01-2025,5.0
18,19,Dev,Gwalior,Monitor,14000.0,Debit Card,23-01-2025,3.0
19,20,Meera,Bhopal,Keyboard,2000.0,UPI,24-01-2025,4.0
21,22,Rahul,Indore,Headphones,3500.0,UPI,07-01-2025,5.0
22,23,Rohit,Delhi,Phone,29000.0,upi,26-01-2025,4.0
23,24,Priya,Bhopal,Tablet,22000.0,Credit Card,NaN,5.0
24,25,Neha,Delhi,Mouse,900.0,NaN,28-01-2025,NaN
25,26,Karan,Jaipur,Laptop,58000.0,UPI,29-01-2025,4.0
28,29,Pooja,Gwalior,Printer,12000.0,Cash,31-01-2025,NaN
29,30,Aarav,NaN,SSD,5500.0,UPI,01-02-2025,6.0
30,31,Riya,Indore,Router,2800.0,Debit Card,02-02-2025,4.0
31,32,Simran,Delhi,Webcam,3000.0,upi,03-02-2025,5.0
32,33,Vivek,Mumbai,Laptop,999999.0,Credit Card,NaN,4.0
33,34,Ananya,Pune,Phone,31000.0,UPI,05-02-2025,5.0
34,35,Mohit,Jaipur,Mouse,850.0,cash,06-02-2025,3.0
35,36,Kavya,Lucknow,NaN,21000.0,Wallet,07-02-2025,4.0
36,37,Nisha,Agra,Headphones,4000.0,UPI,08-02-2025,5.0
37,38,Dev,Gwalior,Monitor,14000.0,Debit Card,09-02-2025,3.0
38,39,Meera,Bhopal,Keyboard,2000.0,UPI,10-02-2025,4.0
39,40,Amit,NaN,Laptop,55000.0,UPI,11-02-2025,5.0
40,41,NaN,Indore,Phone,28000.0,Credit Card,12-02-2025,4.0
41,42,Rohan,Mumbai,Monitor,NaN,Debit Card,13-02-2025,4.0
42,43,Sneha,Pune,Tablet,22000.0,NaN,NaN,5.0
44,45,Isha,Lucknow,Smartwatch,6000.0,UPI,15-02-2025,4.0
45,46,Arjun,Agra,Camera,42000.0,Credit Card,16-02-2025,5.0
46,47,Pooja,NaN,Printer,12000.0,Cash,17-02-2025,NaN
47,48,Aarav,Bhopal,SSD,5500.0,UPI,18-02-2025,4.0
48,49,Riya,Indore,Router,2800.0,Debit Card,19-02-2025,3.0
49,50,Simran,Delhi,Webcam,3000.0,UPI,20-02-2025,5.0

In [74]:
df.duplicated(subset=["city", "amount"])

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22    False
23    False
24    False
25    False
26     True
27     True
28     True
29    False
30    False
31     True
32    False
33     True
34     True
35     True
36     True
37     True
38     True
39    False
40    False
41    False
42    False
43     True
44     True
45     True
46    False
47     True
48     True
49     True
dtype: bool

In [75]:
# string operation with .str
df["customer_name"].str.lower()

0       amit
1       amit
2      rahul
3       neha
4      rohan
5      sneha
6      karan
7       isha
8      arjun
9      pooja
10     aarav
11      riya
12    simran
13     vivek
14    ananya
15     mohit
16     kavya
17     nisha
18      dev
19     meera
20    ananya
21     rahul
22     rohit
23     priya
24      neha
25     karan
26     nisha
27      dev
28     pooja
29     aarav
30      riya
31    simran
32     vivek
33    ananya
34     mohit
35     kavya
36     nisha
37       dev
38     meera
39      amit
40       NaN
41     rohan
42     sneha
43    ananya
44      isha
45     arjun
46     pooja
47     aarav
48      riya
49    simran
Name: customer_name, dtype: str

In [77]:
df["city"].str.contains("delhi",case=False)

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24     True
25    False
26    False
27    False
28    False
29    False
30    False
31     True
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49     True
Name: city, dtype: bool

In [79]:
# Type Conversions with .astype()

In [92]:
df["rating"] = df["rating"].fillna(0).astype(int)

In [94]:
df["order_date"] = pd.to_datetime(df["order_date"], format="%d-%m-%Y")

In [93]:
df.dtypes

order_id                   int64
customer_name                str
city                         str
product                      str
amount                   float64
payment_method               str
order_date        datetime64[us]
rating                     int64
dtype: object

In [95]:
# Applying functions

In [102]:
# .apply() -> Apply any function to rows or columns
df["amount rating"] = df["amount"].apply(lambda x: 5 if x >= 25000 else 4)

In [107]:
df[["amount", "amount rating"]].head(10)

    amount  amount rating
0  55000.0              5
1  55000.0              5
2   3500.0              4
3      NaN              4
4  15000.0              4
5  22000.0              4
6   1800.0              4
7   6000.0              4
8  42000.0              5
9  12000.0              4

In [108]:
# .map() -> element wise mapping for series 
df["payment_code"] = df["payment_method"].map({
    "UPI": 1,
    "Credit Card": 2,
    "Debit Card": 3,
    "Cash": 4,
    "Net Banking": 5
})

In [109]:
df[["payment_method", "payment_code"]].head(10)

  payment_method  payment_code
0            UPI           1.0
1            UPI           1.0
2            UPI           1.0
3           Cash           4.0
4     Debit Card           3.0
5            UPI           1.0
6         Wallet           NaN
7            UPI           1.0
8    Credit Card           2.0
9           Cash           4.0

In [110]:
# .replace() -> Replace sepecific values
df["payment_method"] = df["payment_method"].replace({
    "upi": "UPI",
    "Upi": "UPI",
    "credit card": "Credit Card",
    "debit card": "Debit Card"
})

In [111]:
df[["payment_method"]].head(10)

  payment_method
0            UPI
1            UPI
2            UPI
3           Cash
4     Debit Card
5            UPI
6         Wallet
7            UPI
8    Credit Card
9           Cash