In [22]:
import pandas as pd

data = {
    'Name' : ['Dev', 'Amit', 'Shubham', 'Jeet'],
    'age' : [21, 20, 22, 19],
    'marks' : [98, 78, 89, 95],
}

In [23]:
df = pd.DataFrame(data)
df

      Name  age  marks
0      Dev   21     98
1     Amit   20     78
2  Shubham   22     89
3     Jeet   19     95

In [24]:
# Sort by values

In [25]:
df.sort_values("Name")

      Name  age  marks
1     Amit   20     78
0      Dev   21     98
3     Jeet   19     95
2  Shubham   22     89

In [ ]:
# Ranking data

In [28]:
df['Rank'] = df['marks'].rank(ascending=False)
print("Ranking Data:")
df

Ranking Data:

      Name  age  marks  Rank
0      Dev   21     98   1.0
1     Amit   20     78   4.0
2  Shubham   22     89   3.0
3     Jeet   19     95   2.0

In [32]:
# Renaming Columns

In [33]:
df = df.rename(columns={'Name': 'Student_Name', 'marks': 'Score'})
print("Renamed Columns:")
df

Renamed Columns:

  Student_Name  age  Score  Rank
0          Dev   21     98   1.0
1         Amit   20     78   4.0
2      Shubham   22     89   3.0
3         Jeet   19     95   2.0

In [34]:
# Renaming Index

In [35]:
df = df.rename(index={0: 'A', 1: 'B', 2: 'C', 3: 'D'})
print("Renamed Index:")
df

Renamed Index:

  Student_Name  age  Score  Rank
A          Dev   21     98   1.0
B         Amit   20     78   4.0
C      Shubham   22     89   3.0
D         Jeet   19     95   2.0

In [36]:
# Changing column order

In [39]:
df = df[['Student_Name', 'Score', 'age', 'Rank']]
print("Changed Column Order:")
df

Changed Column Order:

  Student_Name  Score  age  Rank
A          Dev     98   21   1.0
B         Amit     78   20   4.0
C      Shubham     89   22   3.0
D         Jeet     95   19   2.0