In [3]:
import pandas as pd

data = {
    "Name" : ["Amit", "Dev", "Nakul", "Rohan"],
    "Maths" : [85, 90, 78, 74],
    "Science" : [88, 92, 80, 89],
    "English" : [92, 89, 94, 86],
}

In [4]:
df = pd.DataFrame(data)
df

    Name  Maths  Science  English
0   Amit     85       88       92
1    Dev     90       92       89
2  Nakul     78       80       94
3  Rohan     74       89       86

In [6]:
# Using Melt
melted = pd.melt(
    df,
    id_vars=['Name'],
    var_name='Subject',
    value_name='Marks'
)
melted

     Name  Subject  Marks
0    Amit    Maths     85
1     Dev    Maths     90
2   Nakul    Maths     78
3   Rohan    Maths     74
4    Amit  Science     88
5     Dev  Science     92
6   Nakul  Science     80
7   Rohan  Science     89
8    Amit  English     92
9     Dev  English     89
10  Nakul  English     94
11  Rohan  English     86

In [17]:
# using Pivot
pivoted = melted.pivot(
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc = 'mean'
).resetindex()

pivoted

TypeError: DataFrame.pivot() got an unexpected keyword argument 'aggfunc'